server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: limits-svc
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      enable-auto-commit: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/limits
    hikari:
      username: limits
      password: limits_pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQL94Dialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
      generate-ddl: true
      show-sql: true
    generate-ddl: true

limit:
  value: 2000

app:
  topic: transaction
  returnTopic: transaction_return

