springdoc:
  swagger-ui:
    path: /swagger-ui.html
  packagesToScan: com.beneti.transactionbff.api
spring:
  redis:
    port: 6379
    host: localhost
    timeout: 5000

limits:
  url: http://localhost:8081